### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by arjunroychowdhury** [mikegrb/WebService-FindMyiPhone#1]
Hi, have you tried this library recently? I have 2 step auth enabled in iCloud, but I've configured an application specific password in iCloud and when I run a sample app, I get the following error:

perl foo.pl 
Connection error: HASH(0x7f91d566b3d0) at /Library/Perl/5.18/WebService/FindMyiPhone.pm line 107.
	WebService::FindMyiPhone::_post('WebService::FindMyiPhone=HASH(0x7f91d402ebb8)', '/initClient', '{"clientContext":{"appName":"FindMyiPhone","appVersion":"1.4"...') called at /Library/Perl/5.18/WebService/FindMyiPhone.pm line 46
	WebService::FindMyiPhone::_get_shard('WebService::FindMyiPhone=HASH(0x7f91d402ebb8)') called at /Library/Perl/5.18/WebService/FindMyiPhone.pm line 38
	WebService::FindMyiPhone::new('WebService::FindMyiPhone', 'username', 'xxx@xxx.com', 'password', 'xxx-xxx-xx') called at foo.pl line 5

My foo.pl:
#!/usr/bin/env perl

use WebService::FindMyiPhone;
my $fmiphone = WebService::FindMyiPhone->new(
    username => 'xxx@xxxx.xxxx',
    password => 'xxx-xxx-xx',
);

my $iphone = $fmiphone->get_device_by( name => "phonename");

**Comment by mikegrb** [comment]
I haven't used it lately.  Thanks for the heads  up I'll take a look this evening or tomorrow evening.

**Comment by mikegrb** [comment]
I'm really sorry about the 1 month plus delay.  I've just pushed a commit that makes location and sending a message work again.  I'll update the docs, changelog, etc and push a new release this weekend.

Of note, send_message is deprecated, there is now play_sound instead which takes one argument, a message to display.

**Comment by arjunroychowdhury** [comment]
@mikegrb thank you so much!

**Comment by Javier12** [comment]
Hi,
Are you sure that this got fixed? I'm getting the same error.

Thanks so much!
